export const programmes = [
    {
      id: 1,
      name: "BCA (AKU)",
      fullName: "Bachelor of Computer Applications",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Build a tech-savvy future with real-world skills.",
      icon: "💻",
      color: "bg-blue-600",
      badge: "Popular",
      university: "Aryabhatta Knowledge University",
      fee: "₹2,21,000",
      about: "A comprehensive three-year undergraduate program split into six semesters focusing on in-depth studies of computer and information technology-related subjects.",
      eligibility: "10+2 with Mathematics as a subject",
      subjects: ["Programming Languages (Java, C++, HTML, SQL)", "Database Management", "Computer Networks", "Web Development", "Software Engineering"],
      careerPaths: ["Software Developer", "Web Designer", "System Administrator", "Database Administrator", "IT Consultant", "Faculty for Computer Science"],
      addOnCourses: ["Advance Web Development Package", "Advance Java Package", "Computer Hardware & Networking", "Ethical Hacking", "Mobile App Development", "Cloud Computing"]
    },
    {
      id: 2,
      name: "BCA (PPU)",
      fullName: "Bachelor of Computer Applications",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Comprehensive education in computer applications.",
      icon: "💻",
      color: "bg-indigo-600",
      university: "Patna University",
      fee: "Contact for details",
      about: "A three-year program covering all aspects of computer applications and modern IT systems.",
      eligibility: "10+2 with Mathematics as a subject",
      subjects: ["Programming Fundamentals", "Database Systems", "Computer Networks", "Web Technologies", "Software Engineering"],
      careerPaths: ["Software Developer", "System Analyst", "Web Developer", "Database Administrator"]
    },
    {
      id: 3,
      name: "BBA (AKU)",
      fullName: "Bachelor of Business Administration",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Develop leadership skills for the business world.",
      icon: "📊",
      color: "bg-green-600",
      university: "Aryabhatta Knowledge University",
      fee: "Contact for details",
      about: "A comprehensive program designed to develop business administration skills.",
      eligibility: "10+2 or equivalent",
      subjects: ["Management Principles", "Accounting", "Marketing", "Human Resources", "Business Law"],
      careerPaths: ["Business Analyst", "Marketing Executive", "Human Resource Manager", "Entrepreneur"]
    },
    {
      id: 4,
      name: "BBA (PPU)",
      fullName: "Bachelor of Business Administration",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Foundation for future business leaders.",
      icon: "📊",
      color: "bg-emerald-600",
      university: "Patna University",
      fee: "Contact for details",
      about: "A program focused on developing management skills for various business domains.",
      eligibility: "10+2 or equivalent",
      subjects: ["Business Communication", "Economics", "Financial Management", "Marketing Management", "Organizational Behavior"],
      careerPaths: ["Business Development Manager", "Marketing Specialist", "Operations Manager", "Entrepreneur"]
    },
    {
      id: 5,
      name: "B.Com (P) (AKU)",
      fullName: "Bachelor of Commerce (Professional)",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Develop expertise in commerce and finance.",
      icon: "💰",
      color: "bg-yellow-600",
      university: "Aryabhatta Knowledge University",
      fee: "Contact for details",
      about: "A specialized commerce program with professional focus.",
      eligibility: "10+2 with Commerce",
      subjects: ["Accountancy", "Business Economics", "Business Law", "Taxation", "Auditing"],
      careerPaths: ["Accountant", "Financial Analyst", "Tax Consultant", "Banking Professional"]
    },
    {
      id: 6,
      name: "B.Sc-IT (PPU)",
      fullName: "Bachelor of Science in Information Technology",
      duration: "3 Years",
      level: "Undergraduate",
      tagline: "Technical education for the IT industry.",
      icon: "🖥️",
      color: "bg-purple-600",
      university: "Patna University",
      fee: "Contact for details",
      about: "A program combining science and information technology.",
      eligibility: "10+2 with Science/Mathematics",
      subjects: ["Computer Programming", "Mathematics", "Systems Analysis", "Database Management", "Web Technologies"],
      careerPaths: ["IT Support Specialist", "Network Administrator", "Web Developer", "Software Tester"]
    },
    {
      id: 7,
      name: "PGDM (AIMA)",
      fullName: "Post Graduate Diploma in Management",
      duration: "2 Years",
      level: "Postgraduate",
      tagline: "Advanced management education for professionals.",
      icon: "🎓",
      color: "bg-red-600",
      university: "All India Management Association",
      fee: "Contact for details",
      about: "A comprehensive management program for aspiring business leaders.",
      eligibility: "Bachelor's degree in any discipline",
      subjects: ["Strategic Management", "Marketing Management", "Financial Management", "Human Resource Management", "Operations Management"],
      careerPaths: ["Business Manager", "Marketing Manager", "Finance Manager", "Operations Manager", "Consultant"]
    },
    {
      id: 8,
      name: "MBA (AKU)",
      fullName: "Master of Business Administration",
      duration: "2 Years",
      level: "Postgraduate",
      tagline: "Advanced business education for future leaders.",
      icon: "🏆",
      color: "bg-orange-600",
      university: "Aryabhatta Knowledge University",
      fee: "Contact for details",
      about: "An advanced program for developing comprehensive management skills.",
      eligibility: "Bachelor's degree with minimum 50% marks",
      subjects: ["Marketing Management", "Financial Management", "Human Resource Management", "Strategic Management", "Operations Research"],
      careerPaths: ["Business Consultant", "Operations Manager", "Marketing Director", "Financial Analyst", "Entrepreneur"]
    },
    {
      id: 9,
      name: "MCA (AKU)",
      fullName: "Master of Computer Applications",
      duration: "2 Years",
      level: "Postgraduate",
      tagline: "Advanced computing education for specialists.",
      icon: "🖥️",
      color: "bg-pink-600",
      university: "Aryabhatta Knowledge University",
      fee: "Contact for details",
      about: "An advanced program covering specialized areas of computer applications.",
      eligibility: "Bachelor's degree in Computer Applications or related field",
      subjects: ["Advanced Programming", "Software Project Management", "Data Warehousing", "Artificial Intelligence", "Machine Learning"],
      careerPaths: ["Software Architect", "Project Manager", "Technology Consultant", "Research Analyst", "Data Scientist"]
    }
  ];